name: astrophd_tutorial

channels:
  - conda-forge
  - intel

dependencies:
  - scipy
  - numpy
  - jupyter
  - astropy
  - matplotlib
  - scikit-learn>=0.19
  - h5py
  - keras>=2.
  - tensorflow
  - pillow
  - pip:
    - git+https://github.com/paris-saclay-cds/ramp-workflow